// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	UUID                 string     `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Data                 *EventData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	User                 *User      `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Event) GetData() *EventData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type EventData struct {
	Title                string               `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	TimeStamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	NotifyBefore         *duration.Duration   `protobuf:"bytes,5,opt,name=NotifyBefore,proto3" json:"NotifyBefore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventData) Reset()         { *m = EventData{} }
func (m *EventData) String() string { return proto.CompactTextString(m) }
func (*EventData) ProtoMessage()    {}
func (*EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *EventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventData.Unmarshal(m, b)
}
func (m *EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventData.Marshal(b, m, deterministic)
}
func (m *EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventData.Merge(m, src)
}
func (m *EventData) XXX_Size() int {
	return xxx_messageInfo_EventData.Size(m)
}
func (m *EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_EventData proto.InternalMessageInfo

func (m *EventData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventData) GetTimeStamp() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStamp
	}
	return nil
}

func (m *EventData) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *EventData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EventData) GetNotifyBefore() *duration.Duration {
	if m != nil {
		return m.NotifyBefore
	}
	return nil
}

type User struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

type Events struct {
	Events               map[string]*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvents() map[string]*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetEventsParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsParams) Reset()         { *m = GetEventsParams{} }
func (m *GetEventsParams) String() string { return proto.CompactTextString(m) }
func (*GetEventsParams) ProtoMessage()    {}
func (*GetEventsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *GetEventsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsParams.Unmarshal(m, b)
}
func (m *GetEventsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsParams.Marshal(b, m, deterministic)
}
func (m *GetEventsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsParams.Merge(m, src)
}
func (m *GetEventsParams) XXX_Size() int {
	return xxx_messageInfo_GetEventsParams.Size(m)
}
func (m *GetEventsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsParams proto.InternalMessageInfo

type DeleteEventParams struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventParams) Reset()         { *m = DeleteEventParams{} }
func (m *DeleteEventParams) String() string { return proto.CompactTextString(m) }
func (*DeleteEventParams) ProtoMessage()    {}
func (*DeleteEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{5}
}

func (m *DeleteEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventParams.Unmarshal(m, b)
}
func (m *DeleteEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventParams.Marshal(b, m, deterministic)
}
func (m *DeleteEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventParams.Merge(m, src)
}
func (m *DeleteEventParams) XXX_Size() int {
	return xxx_messageInfo_DeleteEventParams.Size(m)
}
func (m *DeleteEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventParams proto.InternalMessageInfo

func (m *DeleteEventParams) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DeleteEventOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventOutput) Reset()         { *m = DeleteEventOutput{} }
func (m *DeleteEventOutput) String() string { return proto.CompactTextString(m) }
func (*DeleteEventOutput) ProtoMessage()    {}
func (*DeleteEventOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{6}
}

func (m *DeleteEventOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventOutput.Unmarshal(m, b)
}
func (m *DeleteEventOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventOutput.Marshal(b, m, deterministic)
}
func (m *DeleteEventOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventOutput.Merge(m, src)
}
func (m *DeleteEventOutput) XXX_Size() int {
	return xxx_messageInfo_DeleteEventOutput.Size(m)
}
func (m *DeleteEventOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*EventData)(nil), "calendar.EventData")
	proto.RegisterType((*User)(nil), "calendar.User")
	proto.RegisterType((*Events)(nil), "calendar.Events")
	proto.RegisterMapType((map[string]*Event)(nil), "calendar.Events.EventsEntry")
	proto.RegisterType((*GetEventsParams)(nil), "calendar.GetEventsParams")
	proto.RegisterType((*DeleteEventParams)(nil), "calendar.DeleteEventParams")
	proto.RegisterType((*DeleteEventOutput)(nil), "calendar.DeleteEventOutput")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x8a, 0xdb, 0x30,
	0x10, 0xc7, 0x71, 0x62, 0x9b, 0x64, 0x5c, 0x92, 0x46, 0xe9, 0xc1, 0x35, 0xa5, 0x35, 0x82, 0x92,
	0x9c, 0x1c, 0x48, 0x5b, 0x08, 0x85, 0x5e, 0x8a, 0x43, 0x69, 0x0f, 0x6d, 0xf1, 0x26, 0x0f, 0xa0,
	0xc4, 0x93, 0xac, 0x59, 0x7f, 0x21, 0x4b, 0x81, 0xbc, 0xc2, 0xbe, 0xee, 0xbe, 0xc0, 0x62, 0x59,
	0xce, 0xd7, 0x1e, 0xf6, 0xa4, 0xd1, 0xcc, 0x6f, 0x46, 0xf3, 0xff, 0x23, 0x18, 0x6c, 0x59, 0x8a,
	0x79, 0xcc, 0x78, 0x50, 0xf2, 0x42, 0x14, 0xa4, 0xd7, 0xde, 0xbd, 0x4f, 0xfb, 0xa2, 0xd8, 0xa7,
	0x38, 0x53, 0xf9, 0x8d, 0xdc, 0xcd, 0x44, 0x92, 0x61, 0x25, 0x58, 0x56, 0x36, 0xa8, 0xf7, 0xf1,
	0x16, 0x88, 0x25, 0x67, 0x22, 0x29, 0xf2, 0xa6, 0x4e, 0xef, 0xc1, 0x5a, 0x1e, 0x30, 0x17, 0x84,
	0x80, 0xb9, 0x5e, 0xff, 0x0e, 0x5d, 0xc3, 0x37, 0xa6, 0xfd, 0x48, 0xc5, 0x64, 0x02, 0x66, 0xcc,
	0x04, 0x73, 0x3b, 0xbe, 0x31, 0x75, 0xe6, 0xe3, 0xe0, 0xb4, 0x86, 0x6a, 0x09, 0x99, 0x60, 0x91,
	0x02, 0x08, 0x05, 0x53, 0x56, 0xc8, 0xdd, 0xae, 0x02, 0x07, 0x67, 0x70, 0x5d, 0x21, 0x8f, 0x54,
	0x8d, 0x3e, 0x19, 0xd0, 0x3f, 0xf5, 0x91, 0x77, 0x60, 0xad, 0x12, 0x91, 0xa2, 0x7e, 0xaf, 0xb9,
	0x90, 0x05, 0xf4, 0x57, 0x49, 0x86, 0x77, 0xb5, 0x00, 0xfd, 0xaa, 0x17, 0x34, 0x0a, 0x82, 0x56,
	0x41, 0xb0, 0x6a, 0x25, 0x46, 0x67, 0x98, 0x7c, 0x83, 0x5e, 0xa8, 0x95, 0xe9, 0x2d, 0xde, 0xbf,
	0x68, 0x6c, 0x81, 0xe8, 0x84, 0x12, 0x1f, 0x9c, 0x10, 0xab, 0x2d, 0x4f, 0x4a, 0xd5, 0x69, 0xaa,
	0x65, 0x2e, 0x53, 0xe4, 0x07, 0xbc, 0xf9, 0x5b, 0x88, 0x64, 0x77, 0xfc, 0x89, 0xbb, 0x82, 0xa3,
	0x6b, 0xbd, 0x36, 0xfc, 0x0a, 0xa7, 0x36, 0x98, 0xb5, 0x07, 0xf4, 0xd1, 0x00, 0x5b, 0xa9, 0xaf,
	0xc8, 0x57, 0xb0, 0x51, 0x45, 0xae, 0xe1, 0x77, 0xa7, 0xce, 0xfc, 0xc3, 0x8d, 0xaf, 0x95, 0x3e,
	0x96, 0xb9, 0xe0, 0xc7, 0x48, 0xb3, 0xde, 0x1f, 0x70, 0x2e, 0xd2, 0xe4, 0x2d, 0x74, 0x1f, 0xf0,
	0xa8, 0xdd, 0xab, 0x43, 0xf2, 0x19, 0xac, 0x03, 0x4b, 0x25, 0x6a, 0xdf, 0x86, 0x37, 0x53, 0xa3,
	0xa6, 0xfa, 0xbd, 0xb3, 0x30, 0xe8, 0x08, 0x86, 0xbf, 0x50, 0x34, 0xe3, 0xfe, 0x33, 0xce, 0xb2,
	0x8a, 0x4e, 0x60, 0x14, 0x62, 0x8a, 0x02, 0x55, 0xb6, 0x49, 0xd6, 0x7f, 0x42, 0xca, 0x24, 0x6e,
	0xff, 0x44, 0x1d, 0xd3, 0xf1, 0x15, 0xf8, 0x4f, 0x8a, 0x52, 0x8a, 0x8d, 0xad, 0x6c, 0xf8, 0xf2,
	0x1c, 0x00, 0x00, 0xff, 0xff, 0x99, 0x36, 0xfc, 0x48, 0xa9, 0x02, 0x00, 0x00,
}
